### ISSUE TITLE
Crash on accepting teleport

### ISSUE THREAD

**Issue by Zero-Shift** [lmcintyre/DamageInfoPlugin#1]
As the title says: I've had 2 crashes happen just now when accepting a teleport. The game freezes as the zone title is fading in during the transition. WinDbg linked the crash to DamageInfoPlugin.dll, and attached is the analyzed crash dump.

[crashdump.txt](https://github.com/lmcintyre/DamageInfoPlugin/files/5046694/crashdump.txt)

**Comment by lmcintyre** [comment]
Thanks for the report. I'll have this fixed soon.

**Comment by lmcintyre** [comment]
This has been fixed in f1fe125. However, with 5.3 occurring, I will tend to 5.3 fixes (if necessary) and do one release to avoid a bunch of updates. Again, thanks for the report, the crashdump made it real easy to fix.
