### ISSUE TITLE
[Suggestion] For incoming damage, also show % mitigation

### ISSUE THREAD

**Issue by czlr** [lmcintyre/DamageInfoPlugin#11]
This would help provide insight on mitigations -- both how much mitigation there is currently, and help you troubleshoot tight timings (e.g., checking if your mitigation is timed correctly to cover say... both a raidwide + the follow up tankbuster)

**Comment by lmcintyre** [comment]
I planned to do this originally, but it would be almost impossible to determine *when* the mitigation took effect. For example, I can just check if the buff was on the enemy. However, this may say something like

Attack Name 5900
                -10% Reprisal
                
However, this would be the case across all actions that are incoming, even if the mitigation did not actually do anything, such as a % HP based attack. This is the reason I never implemented it. If someone finds a way to determine if any mitigation actually took place, that would allow me to implement it.
