### ISSUE TITLE
Samurai and Dragoon positionals wrong way round

### ISSUE THREAD

**Issue by Enzemo** [lmcintyre/DamageInfoPlugin#13]
For Samurai the positional text shows green when doing Gekko from the flank 
![image](https://user-images.githubusercontent.com/11069930/181302566-ef2e8585-301a-4e49-a5fd-354d9428c6dc.png)
(it's a rear move)

And for Kasha, it shows green when doing Kasha from the rear, when it's a flank move
![image](https://user-images.githubusercontent.com/11069930/181302652-ae34b091-3618-4bb2-911f-f4aed8d5a7f3.png)

![image](https://user-images.githubusercontent.com/11069930/181302818-032e5e04-35db-4b2e-b3e4-943d6c9d83d8.png)

**Comment by Enzemo** [comment]
It seems to be the wrong way round for Dragoon too

**Comment by lmcintyre** [comment]
Do you have the setting to color only missed positionals enabled?

**Comment by Enzemo** [comment]
Yeah I just realised my mistake sorry
