### ISSUE TITLE
About Auto Attack

### ISSUE THREAD

**Issue by torakiti2017** [lmcintyre/DamageInfoPlugin#17]
Is it possible to hide the fly text of the auto attack or set the color individually?
I would like to make the auto attack damage inflicted by itself less noticeable as I don't pay much attention to it.

**Comment by lmcintyre** [comment]
I would recommend using the plugin FlyTextFilter for this.

**Comment by torakiti2017** [comment]
Thanks for the info.
Appreciate it.
