### ISSUE TITLE
Localize "from [Actor]" flytext to client language

### ISSUE THREAD

**Issue by Krude** [lmcintyre/DamageInfoPlugin#2]
While having the whole plugin UI localized would be nice, it's probably also a big hassle requiring large rewrites and hunting for translations in who knows how many languages. Don't do that.

But DamageInfo integrates text into the game's UI, even if it's just the single word "from", which clashes with the rest of the game's UI when you're not playing in English. It would be nice to see the few translations into DE/FR/JP (maybe CN? lol) for the "from" source to make it fit seamlessly into the client.

German would be "von", French would be "de" or "par" (i am not French and my last lesson was 15 years ago so double check that), and i have no clue about Japanese.

**Comment by Kaiay** [comment]
Is this the reason of showing "＝" in the skills names of flytext?
just start using DamageInfoPlugin and find that the japanese skills names can't display properly.

**Comment by lmcintyre** [comment]
I have no idea how I didn't get notified about this issue. Usually I get stuff like this sent directly to my e-mail, but I missed this one. Thanks for letting me know; I've been wondering how best to do this for a while now. I will look further into this and attempt to fix Japanese monster names at the same time.

**Comment by lmcintyre** [comment]
This issue has been fixed. Thanks for the report.

@Kaiay I made some changes to how actor names are displayed in 1.3.6.0. Please update and give it a try, and if you still get "=" in the monster names, feel free to open a new issue.
