### ISSUE TITLE
[Feature Request] Option to add sounds to positionals

### ISSUE THREAD

**Issue by x3nobyte** [lmcintyre/DamageInfoPlugin#20]
It would be great to have an option to add sound to either hit or miss of positionals.

**Comment by lmcintyre** [comment]
Hi! This feature will be included in the update to Damage Info after patch 6.5 is released. You will be able to set a positional hit and miss sound at the same time, if you wish, and set the sound to any of the chat sound effects (the `<se.X>` sounds). Thanks for the suggestion!
