### ISSUE TITLE
Samurai's positionals are always being displayed as "missed"

### ISSUE THREAD

**Issue by Yurei17** [lmcintyre/DamageInfoPlugin#23]
Samurai's positionals are always being displayed as missed despite hitting the appropriate positional. This issue only happens after level 90+, when I sync to an older piece of content, the positionals work as intended.

**Comment by DoctorXIV** [comment]
This isn't updated from 7.0 yet is it?

**Comment by lmcintyre** [comment]
There is a version in testing.

**Comment by DoctorXIV** [comment]
ahh ok that makes sense.

**Comment by Yurei17** [comment]
Some positional logs:
[DamageInfoPlugin] Action: Kasha [7482] jobLevel: 100 boostPercent: 59 positionalState: Failure. -> hit the flank
[DamageInfoPlugin] Action: Gekko [7481] jobLevel: 100 boostPercent: 59 positionalState: Failure. -> hit the rear
[DamageInfoPlugin] Action: Gekko [7481] jobLevel: 100 boostPercent: 53 positionalState: Failure -> missed on purpose
[DamageInfoPlugin] Action: Kasha [7482] jobLevel: 100 boostPercent: 53 positionalState: Failure. -> missed on purpose

**Comment by Yurei17** [comment]
issue has been resolved 👍
