### ISSUE TITLE
Spamming blank chat messages

### ISSUE THREAD

**Issue by ChumpChange123** [lmcintyre/DamageInfoPlugin#27]
While this plugin is running my chat goes crazy with a bunch of blank spaces. I don't really know what is causing them. It happens while crafting, doing battle content, or even just walking around. Normal chat messages will still show up
![image_2024-07-14_151503272](https://github.com/user-attachments/assets/be957160-b7c5-4cbe-8bf3-8a80e4aa3c99)

**Comment by lmcintyre** [comment]
This doesn't happen to me and I have not had any reports of this happening from anyone else. Are you certain it's damage info doing this?

**Comment by ChumpChange123** [comment]
I individually turned off each plugin I had installed and waited a few minutes to make sure the issue kept occurring and it was only when I turned off damage info that it stopped happening. 

Do you have any advice / a better method for trying to isolate and confirm if it's damage info?
