### ISSUE TITLE
Plugin Suggestion

### ISSUE THREAD

**Issue by khaoslbc** [lmcintyre/DamageInfoPlugin#3]
Adding further customization:
-Damage numbers without spell names/text
-Changeable fonts 
-Removeable Icons for spell popups

**Comment by lmcintyre** [comment]
Hi, thanks for the suggestions. I've already added the ability to remove spell names in 1.3.7.0 available on the plugin installer right now - let me know if you have any suggestions for how that works.

Changeable fonts - we are restricted to the fonts that XIV uses in-game, but I will take a look and see what is possible. I actually thought of this the other day as well, so it will be cool to try.

Removable icons - I am a bit unclear on this, do you mean removing icons from the buff fly text? i.e. when using Sprint, do not show the Sprint icon, but show the `+ Sprint` text? In the same vein, I was considering adding an option to remove text for incoming buffs, incoming heals, and incoming MP recovery.

**Comment by khaoslbc** [comment]
Hello, I have used the new iteration of your plugin, it is amazing with the spell name text removed, less clutter is a good thing.

Removable icons - Yes you are correct, removing the icons from the buff fly text would be warranted, also the removable of the text would be good also, considering we already have the buff icon in a static location within the UI, thus making it redundant.

The option for removing the text from incoming buffs, heals and HP/MP recovery would be amazing also.

Thank you for your hard work, hoping to see further progress of this amazing plugin.

**Comment by Jungleau1** [comment]
Yeah having the flying text and completely removing flying buffs entirely would be a use gamechanger in clearing up the screen.

**Comment by lmcintyre** [comment]
This is an old issue, but you should be able to use FlyTextFilter to remove any fly text with an icon. Font changing is not on my list at the moment. Sorry.
