### ISSUE TITLE
Target HP

### ISSUE THREAD

**Issue by jj94523** [lmcintyre/DamageInfoPlugin#6]
Is there a way to show percentage of health instead of numbers? Ex: 60% instead of 60.8k I can only find numbers in the drop-down menu.

**Comment by lmcintyre** [comment]
Hi, target HP is from SimpleTweaks, not Damage Info. SimpleTweaks can be found here: https://github.com/caraxi/simpletweaksplugin

**Comment by jj94523** [comment]
Sorry!
