### ISSUE TITLE
JP client monster name font broken

### ISSUE THREAD

**Issue by happypotatoC** [lmcintyre/DamageInfoPlugin#7]
![ffxiv_08122021_133818_703](https://user-images.githubusercontent.com/46651278/129144402-6a6c8890-fa1a-4392-973b-1678a10a7b15.png)
![ffxiv_08122021_145811_790](https://user-images.githubusercontent.com/46651278/129145660-00eb3f44-f999-4071-96fa-3fc4ac93fd46.png)

The names of all monsters are output to ' = '
What should I do? ><

**Comment by lmcintyre** [comment]
Hi! Sorry about this bug. My method of reading the enemy name was broken by a change in Dalamud. This is fixed in my development build for Dalamud on .NET 5, and I was not planning on fixing it before then. Unfortunately, I would recommend turning off source text for now.

**Comment by happypotatoC** [comment]
thank you always！
