### ISSUE TITLE
Suggestion - hide incoming

### ISSUE THREAD

**Issue by joerithienpont** [lmcintyre/DamageInfoPlugin#8]
Hey,

I like the plugin but I really wanted it to hide incoming damage and healing. 
Could you add an alpha setting for those? Because currently you style all or nothing.
My goal is only view my outgoing damage and nothing else.

regards

**Comment by nyxalteria** [comment]
agreed, incoming healing is very very annoying, seeing who its from

**Comment by lmcintyre** [comment]
You can use FlyTextFilter for this.
