### ISSUE TITLE
No attack name for outgoing flying text if recolored to match damage type without Attack Text ticked

### ISSUE THREAD

**Issue by Otaku-2** [lmcintyre/DamageInfoPlugin#9]
using the plugin with the Outgoing Damage Color tickbox checked, without Attack Text ticked.
![image](https://user-images.githubusercontent.com/21027484/148636758-2dd2f1df-2275-4bd4-9de8-0b404e488d82.png)
not having the plugin, or unticking the Outgoing Damage Color tickbox.
![image](https://user-images.githubusercontent.com/21027484/148636760-98e9026a-8978-4453-a4eb-2b784321600b.png)
using the plugin and having both Outgoing Damage Color and Attack Text boxes ticked.
![image](https://user-images.githubusercontent.com/21027484/148636867-21fab518-c641-462d-aac8-fd1e8a9f23d8.png)

**Comment by lmcintyre** [comment]
This should be fixed. Please open a new issue if not.
